use_frameworks!

platform :ios, '10.0'

target 'MSButton_Example' do
  pod 'MSButton', :path => '../'

  target 'MSButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
